In [44]:
def bf_2sum(A, T):
    n = len(A)
    for i in range (n):
        for j in range (i, n):
            if  A[i] + A[j] == T:
                return True

    return False

In [45]:
A = [1,4,6,3,8,2,0,-1]
B = [-2,-4,5,2,0,7]
bf_2sum(B, 20)

False

In [46]:
bf_2sum(A, 7)

True

In [47]:
def binary_sesarch(A, T):
    low = 0
    n = len(A)
    high = n - 1
    mid = 0

    while low <= high:
        mid = (high + low )//2
        if A[mid] < T:
            low = mid +1
        elif A[mid] > T:
            high = mid - 1
        else:
            return True
    return False

In [48]:
def bs_2sum(A, T):
    n = len(A)
    A.sort()
    for i in range (n):
        return binary_sesarch(A, T - A[i])

In [49]:
bs_2sum(B, 20)

False

In [50]:
bs_2sum(A, 7)

True

In [51]:
def greedy_2sum(A, T):
    A.sort()
    n = len(A)
    i = 0
    j = n - 1
    while i <= j:
        sum = A[i] + A[j]
        if sum > T:
            j = j - 1
        elif sum < T:
            i = i + 1
        else:
            return True
    return False


In [52]:
greedy_2sum(B, 20)

False

In [53]:
greedy_2sum(A, 7)

True

In [54]:
def greedy_2sum2(A, T):
    n = len(A)
    i = 0
    j = n - 1
    while i <= j:
        sum = A[i] + A[j]
        if sum > T:
            j = j - 1
        elif sum < T:
            i = i + 1
        else:
            return True
    return False


In [55]:
def reduce_3sum(A, T):
    A.sort()
    n = len(A)
    for i in range (n):
        return greedy_2sum2(A, T - A[i])


In [56]:
reduce_3sum(A, 9)

True

In [57]:
reduce_3sum(B, 20)

False

In [58]:
def zero_3sum(A):
    A.sort()
    n = len(A)
    for i in range (n):
        return greedy_2sum2(A, 0 - A[i])

In [59]:
def zero_3sum2(A):
    n = len(A)
    for i in range (n):
        return greedy_2sum2(A, 0 - A[i])

In [60]:
zero_3sum(A)

True

In [61]:
zero_3sum(B)

True

In [62]:
C = [-2, 3, 5, 7, 6]
zero_3sum(C)

False

In [63]:
def reduced_3sum_3zero(A, T):
    A.sort()
    n = len(A)
    B = []
    for i in range (n):
        B.append(0)
    for i in range(n):
        B[i] = 3*A[i] - T
    return zero_3sum2(B)

# a[i] + a[j] + a[k] = T
# 3a[i] + 3[aj] + 3a[k] - 3T = 0
# (3a[i] - T) + (3a[j] - T) + (3a[k] - T) = 0

In [64]:
reduced_3sum_3zero(A, 7)

True

In [65]:
reduced_3sum_3zero(B, 20)

False

In [66]:
import numpy
def reduced_3array(A, B, C):
    n = len(A)
    D = []
    E = []
    F = []
    for i in range (n):
        D.append(0)
        E.append(0)
        F.append(0)
    for i in range (n):
        D[i] = 10 * A[i] + 1
        E[i] = 10 * B[i] + 2
        F[i] = 10 * C[i] - 3
    G = numpy.concatenate((A, B, C), axis = None)
    print(G)
    return zero_3sum2(G)

# multiply by 10 preserves sets of elements that sum to 0
# add + 1: elements in A mod 10 = 1
# add + 2: elements in B mod 10 = 2
# add - 3: elements in C mod 10 = 7
# so only way is to pick one from each subarray


In [67]:
def twoSum(nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
        n = len(nums)
        i = 0
        j = n - 1
        temp = []
        for k in range (n):
            temp.append(nums[k])
        temp.sort()
        
        while i <= j:
            sum = temp[i] + temp[j] 
            if sum > target:
                j = j - 1
            elif sum < target:
                i = i + 1
            else:
                res_i = i
                res_j = j
                break
        for i in range (n):
            if nums[i] == temp[res_i]:
                res_i = i
                break
        for j in range (n):
            if j == res_i:
                continue
            if nums[j] == temp[res_j]:
                res_j = j
                break
        
        return [res_i, res_j]

In [68]:
twoSum([3,2,4],6)

[1, 2]

In [69]:
twoSum([3,3],6)

[0, 1]

In [70]:
twoSum([3,2,3],6)

[0, 2]

In [71]:
D = [2,-2,-1]
E = [8,3,5]
F = [6,4,7]
reduced_3array(D,E,F)

[ 2 -2 -1  8  3  5  6  4  7]


False

In [72]:
G = [2,-2,-1]
H = [8,3,5]
I = [-1,4,7]
reduced_3array(G,H,I)

[ 2 -2 -1  8  3  5 -1  4  7]


False

In [73]:
def runningSum(nums):
        """
        :type nums: List[int]
        :rtype: List[int]
        """
        
        n = len(nums)
        res = []
        
        for i in range(n):
            res.append(0)
        
        res[0] = nums[0]
        sum = nums[0]
        
        for i in range(1, n):
            sum = sum + nums[i]
            res[i] = sum
            
        return res

In [74]:
runningSum([1,2,3,4])

[1, 3, 6, 10]

In [75]:
runningSum([1,1,1,1,1])

[1, 2, 3, 4, 5]

In [76]:
runningSum([3,1,2,10,1])

[3, 4, 6, 16, 17]

In [77]:
def reduced_square(A,B,C):
    n = len(A)
    
    D = []
    E = []
    F = []
    for i in range(n):
        D.append(A[i] * A[i] * -1)
        E.append(B[i] * B[i] * -1)
        F.append(C[i] * C[i])

    return reduced_3array(D,E,F)


In [78]:
A = [3, 19, 21]
B = [4, 2, 9]
C = [2, 5, 10]
reduced_square(A,B,C)

[  -9 -361 -441  -16   -4  -81    4   25  100]


False